version: 2

#
# YAML variable templates
#
job_defaults: &job_defaults
  working_directory: ~/gruvboxui
  docker:
    - image: circleci/node:lts

#
# Run all jobs in sequence
#
workflows:
  version: 2
  deploy_npm:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master

      - test:
          filters:
            branches:
              only:
                - master
          requires:
            - setup

      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - test

#
# Define atomic jobs
#
jobs:
  setup:
    <<: *job_defaults

    steps:
      - checkout

      - run:
          name: "gruvbox-ui: Install npm packages"
          command: "npm run setup:ci"

      - run:
          name: "gruvbox-ui: Babel compile"
          command: "npm run build"

      - save_cache:
          paths:
            - node_modules
            - src
            - dist
            - .git
            - .babelrc
            - .eslintrc
            - .gitignore
            - .prettierrc
            - README.md
            - CHANGELOG.md
            - LICENSE
            - package-lock.json
            - package.json
          key: gruvbox-ui-{{ .Branch }}-{{ .Revision }}

  test:
    <<: *job_defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - gruvbox-ui-{{ .Branch }}-{{ .Revision }}

      - run:
          name: "gruvbox-ui: Run linter"
          command: "npm run lint"

  publish:
    <<: *job_defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - gruvbox-ui-{{ .Branch }}-{{ .Revision }}

      - run:
          name: "gruvbox-ui: Release to npm with semantic-release"
          command: "npm run publish"

