name: Publish to NPM
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      node-modules-cache-key: ${{ steps.node-modules-cache-key.outputs.key }}
      node-version: ${{ steps.nvmrc.outputs.node_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read .nvmrc
        id: nvmrc
        run: echo "node_version=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Generate node_modules cache key
        env:
          # Increment manually for cache busting
          CACHE_VERSION: "v3"
        id: node-modules-cache-key
        run: echo "key=${{ runner.os }}-node-modules-$(cat package-lock.json | shasum -a 256 | cut -d ' ' -f 1)-${{ env.CACHE_VERSION }}" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvmrc.outputs.node_version }}
          cache: "npm"

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ steps.node-modules-cache-key.outputs.key }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm clean-install

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ needs.setup.outputs.node-modules-cache-key }}

      - name: Run linting
        run: npm run lint

  typecheck:
    name: Typecheck
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ needs.setup.outputs.node-modules-cache-key }}

      - name: Run type checking
        run: npm run typecheck

  unit-test:
    name: Unit Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ needs.setup.outputs.node-modules-cache-key }}

      - name: Run unit testing
        run: npm run unit-test

  release:
    name: Release
    needs: [setup, lint, typecheck, unit-test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ needs.setup.outputs.node-modules-cache-key }}

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Build project
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASD14_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
